if whisperfile, do not ask for whsiper.cpp

diff --git a/wsi b/wsi
--- a/wsi
+++ b/wsi
@@ -13,7 +13,7 @@
 
 # NAME: wsi 
 # PREREQUSITES: 
-#  - whisper.cpp installation (see https://github.com/ggerganov/whisper.cpp) 
+#  - whisper.cpp installation (see https://github.com/ggerganov/whisper.cpp) or a portable whisperfile
 #  - recent versions of 'sox', 'curl', 'xsel' or 'wl-copy' CLI tools from your system's repositories.
 #--------------------------------------------------------------------------
 
@@ -36,7 +36,7 @@ NTHR=8
 #NTHR=$(( $(getconf _NPROCESSORS_ONLN) / 2 ))
 # Use PRIMARY selection (middle mouse button to paste) unless CLIPBOARD selected: 
 CLIPBOARD=false
-# Use available whisperfile (downloaded to a folder in the PATH and set to executable)
+# Uncomment to use available whisperfile (downloaded to a folder in the PATH and set to executable)
 WHISPERFILE=whisper-tiny.en.llamafile 
 # (For the next one need to compile blahste.c, supplied, works only on X11 for now).
 # Change to 'true' to paste automatically on completed transcription (using 'blahste'):
@@ -47,29 +47,7 @@ WHOST="127.0.0.1"
 WPORT="58080"             
 #---END USER CONFIG BLOCK------------------------------------------------------------------------
 
-#---CHECK DEPENDENCIES. This block can be commented out once dependencies confirmed-----------------------------------
-command -v curl &>/dev/null || { echo "curl is required. Please, install curl" >&2 ; exit 1 ; }
-#The next is only needed if curl requests json output from the whisper.cpp server;
-#command -v jq &>/dev/null || { echo "jq is required. Please, install jq" >&2 ; exit 1 ; }
-command -v sox &>/dev/null || { echo "sox is required. Please, install sox" >&2 ; exit 1 ; }
-command -v transcribe &>/dev/null || { echo -e "Please, install whisper.cpp (see https://github.com/ggerganov/whisper.cpp)\
-\nand create 'transcribe' in your PATH as a symbolic link to the main executable, e.g.\n \
- 'ln -s /full/path/to/whisper.cpp/main \$HOME/.local/bin/transcribe'" >&2 ; exit 1 ; }
-#Now let's check if we are in X11 or Wayland and use the right utility:
-if [[ wm == "wayland" ]]; then
-    command -v wl-copy &>/dev/null || { echo "wl-copy is needed for the clipboard. Please, install wl-copy" >&2 ; exit 1 ; } 
-elif [[ wm == "X11" ]]; then
-    command -v xsel &>/dev/null || { echo "We rely on xsel for the clipboard. Please, install xsel." >&2 ; exit 1 ; }
-fi
-#This is needed if wsi is used with Blurt (GNOME shell extension):
-#gsettings --schemadir /home/u1/.local/share/gnome-shell/extensions/blurt@quantiusbenignus.local/schemas/ get org.gnome.shell.extensions.blurt use-api &> /dev/null || { echo "This \
-# script is made to work with Blurt (GNOME shell extension). Please, install it from https://extensions.gnome.org/extension/6742/blurt/"; exit 1 ; }
-#---END CHECK DEPENDENCIES. The above block can be commented out after successful 1st run----------------------------
-
-#Hear the complaints of the above tools and do not continue with the sequence:
-set -e
-
-# Process command line arguments
+# Process command line arguments first
 while [ $# -gt 0 ]; do
     case "$1" in
         -c|--clipboard)
@@ -110,6 +88,23 @@ while [ $# -gt 0 ]; do
     esac
 done
 
+#---CHECK DEPENDENCIES. This block can be commented out once dependencies confirmed-----------------------------------
+command -v curl &>/dev/null || { echo "curl is required. Please, install curl" >&2 ; exit 1 ; }
+command -v sox &>/dev/null || { echo "sox is required. Please, install sox" >&2 ; exit 1 ; }
+[ -n $whf ] || command -v transcribe &>/dev/null || { echo -e "Please, install whisper.cpp (see https://github.com/ggerganov/whisper.cpp)\
+\nand create 'transcribe' in your PATH as a symbolic link to the main executable, e.g.\n \
+ 'ln -s /full/path/to/whisper.cpp/main \$HOME/.local/bin/transcribe'" >&2 ; exit 1 ; }
+#Now let's check if we are in X11 or Wayland and use the right utility:
+if [[ wm == "wayland" ]]; then
+    command -v wl-copy &>/dev/null || { echo "wl-copy is needed for the clipboard. Please, install wl-copy" >&2 ; exit 1 ; } 
+elif [[ wm == "X11" ]]; then
+    command -v xsel &>/dev/null || { echo "We rely on xsel for the clipboard. Please, install xsel." >&2 ; exit 1 ; }
+fi
+#---END CHECK DEPENDENCIES. The above block can be commented out after successful 1st run----------------------------
+
+#Hear the complaints of the above tools and do not continue with the sequence:
+set -e
+
 rec -q -t wav $ramf rate 16k silence 1 0.1 1% 1 2.0 5%  2>/dev/null
 
 #The server inference has precedence (i.e. -w will be ignored if -n is present). 
@@ -121,7 +116,7 @@ if [ -n "$IPnPORT" ]; then
         -F temperature_inc="0.2" \
         -F response_format="text")
 # | jq -r '.text' )
-elif [[ "$whf" == *.llamafile ]]; then
+elif [[ "$transcribe" == *.llamafile ]]; then
     #echo "Using whisperfile: "
     str="$($whf -t $NTHR -nt -f $ramf 2>/dev/null)"  
 else
