desktop notify when no server

diff --git a/wsi b/wsi
--- a/wsi
+++ b/wsi
@@ -37,8 +37,8 @@ NTHR=8
 #NTHR=$(( $(getconf _NPROCESSORS_ONLN) / 2 ))
 # Use PRIMARY selection (middle mouse button to paste) unless CLIPBOARD selected (here or via CLI flag -c): 
 CLIPBOARD=false
-# Uncomment to use available whisperfile (downloaded to a folder in the PATH and set to executable)
-WHISPERFILE=whisper-tiny.en.llamafile 
+# Uncomment to use available whisperfile (downloaded to a folder in the PATH and set to executable):
+# WHISPERFILE=whisper-tiny.en.llamafile 
 # (For the next one need to compile blahste.c, supplied, works only on X11 for now).
 # Change to 'true' to paste automatically on completed transcription (using 'xdotool'):
 AUTOPASTE=false
@@ -46,7 +46,29 @@ AUTOPASTE=false
 #(Can be overwritten when command line argument IP:PORT is supplied instead of '-n')
 WHOST="127.0.0.1"
 WPORT="58080"             
-#---END USER CONFIG BLOCK------------------------------------------------------------------------
+#---END USER CONFIGURATION BLOCK--------------------------------------------------------------------
+
+#---CHECK DEPENDENCIES. This block can be commented out once dependencies confirmed-----------------------------------
+command -v curl &>/dev/null || { echo "curl is required. Please, install curl" >&2 ; exit 1 ; }
+command -v sox &>/dev/null || { echo "sox is required. Please, install sox" >&2 ; exit 1 ; }
+[ -n $WHISPERFILE ] || command -v transcribe &>/dev/null || { echo -e "Please, install whisper.cpp (see https://github.com/ggerganov/whisper.cpp)\
+\nand create 'transcribe' in your PATH as a symbolic link to the main executable, e.g.\n \
+ 'ln -s /full/path/to/whisper.cpp/main \$HOME/.local/bin/transcribe'" >&2 ; exit 1 ; }
+# We will use notify-send (part of libnotify or libnotify-bin in some distros) for desktop notifications:
+command -v notify-send &>/dev/null || { echo "notify-send is needed for error reporting. Please, install libnotify-bin" >&2 ; exit 1 ; }
+#Now let's check if we are in X11 or Wayland and use the right utility:
+if [[ wm == "wayland" ]]; then
+    command -v wl-copy &>/dev/null || { echo "wl-copy is needed for the clipboard. Please, install wl-copy" >&2 ; exit 1 ; } 
+    if [ "$AUTOPASTE" = true ]; then 
+       command -v ydotool &>/dev/null || { echo "To have the transcribed text pasted automatically at the cursor position, please install ydotool" >&2 ; exit 1 ; }
+    fi
+elif [[ wm == "X11" ]]; then
+    command -v xsel &>/dev/null || { echo "We rely on xsel for the clipboard. Please, install xsel." >&2 ; exit 1 ; }
+    if [ "$AUTOPASTE" = true ]; then 
+       command -v xdotool &>/dev/null || { echo "To have the transcribed text pasted automatically at the cursor position, please install xdotool" >&2 ; exit 1 ; }
+    fi
+fi
+#---END CHECK DEPENDENCIES. The above block can be commented out after successful 1st run----------------------------
 
 # Process command line arguments first
 while [ $# -gt 0 ]; do
@@ -64,7 +86,8 @@ while [ $# -gt 0 ]; do
             #Can be overwritten with a supplied command-line argument IP:PORT instead of this option
             IPnPORT="$WHOST:$WPORT" 
             if [[ "$(curl -s -f -o /dev/null -w '%{http_code}' $IPnPORT)" != "200" ]]; then
-                echo "Can't connect to whisper.cpp server at provided address!" >&2   
+                echo "Can't connect to whisper.cpp server at provided address!" >&2  
+                notify-send "No connection to Whisper.cpp server" "No whisper.cpp server at $IPnPORT."   
                 exit 1
             fi
             shift
@@ -82,32 +105,13 @@ while [ $# -gt 0 ]; do
             IPnPORT=$1
             if [[ "$(curl -s -f -o /dev/null -w '%{http_code}' $IPnPORT)" != "200" ]]; then
                 echo "Can't connect to a whisper.cpp server at provided address!" >&2   
+                notify-send "No connection to Whisper.cpp server" "No whisper.cpp server at $IPnPORT."   
                 exit 1
             fi
             shift
             ;;
     esac
 done
-
-#---CHECK DEPENDENCIES. This block can be commented out once dependencies confirmed-----------------------------------
-command -v curl &>/dev/null || { echo "curl is required. Please, install curl" >&2 ; exit 1 ; }
-command -v sox &>/dev/null || { echo "sox is required. Please, install sox" >&2 ; exit 1 ; }
-[ -n $whf ] || command -v transcribe &>/dev/null || { echo -e "Please, install whisper.cpp (see https://github.com/ggerganov/whisper.cpp)\
-\nand create 'transcribe' in your PATH as a symbolic link to the main executable, e.g.\n \
- 'ln -s /full/path/to/whisper.cpp/main \$HOME/.local/bin/transcribe'" >&2 ; exit 1 ; }
-#Now let's check if we are in X11 or Wayland and use the right utility:
-if [[ wm == "wayland" ]]; then
-    command -v wl-copy &>/dev/null || { echo "wl-copy is needed for the clipboard. Please, install wl-copy" >&2 ; exit 1 ; } 
-    if [ "$AUTOPASTE" = true ]; then 
-       command -v ydotool &>/dev/null || { echo "To have the transcribed text pasted automatically at the cursor position, please install ydotool" >&2 ; exit 1 ; }
-    fi
-elif [[ wm == "X11" ]]; then
-    command -v xsel &>/dev/null || { echo "We rely on xsel for the clipboard. Please, install xsel." >&2 ; exit 1 ; }
-    if [ "$AUTOPASTE" = true ]; then 
-       command -v xdotool &>/dev/null || { echo "To have the transcribed text pasted automatically at the cursor position, please install xdotool" >&2 ; exit 1 ; }
-    fi
-fi
-#---END CHECK DEPENDENCIES. The above block can be commented out after successful 1st run----------------------------
 
 #Hear the complaints of the above tools and do not continue with the sequence:
 set -e
